### ISSUE TITLE
"Ghost" feedback messages

### ISSUE THREAD

**Issue by kav2k** [DJDavid98/Deviant-Notify#8]
Might be related to #7, but: since the release of 1.5.0 (I think) I have unclearable unread notifications:

![image](https://user-images.githubusercontent.com/1549691/152178485-9dfadfe3-a6ba-453b-9d7b-214165697030.png)
At the same time, the badge shows 25

Doesn't look like I'm having this "beta" new Notification center, at least I don't see it on the site and the extension does not detect it.

Trying to reset unreads or mark all as read doesn't clear this state.

**Comment by WentTheFox** [comment]
I'm extremely busy until the weekend, for now you can try to uninstall and reinstall the extension, but if that doesn't fix it, this might take me a few days to get sorted.

**Comment by kav2k** [comment]
No problem, it's not urgent! Just wanted to make you aware of it.

Reinstall didn't help. I'm attaching a dump of the storage before reinstall.

[localStorage_storage_Deviant-Notify.json.txt](https://github.com/DJDavid98/Deviant-Notify/files/7989558/localStorage_storage_Deviant-Notify.json.txt)
[sync_storage_Deviant-Notify.json.txt](https://github.com/DJDavid98/Deviant-Notify/files/7989560/sync_storage_Deviant-Notify.json.txt)

**Comment by WentTheFox** [comment]
v1.5.1 has just been pushed to the extension sites which should resolve this issue, if it does not work for you please reopen the issue.

**Comment by kav2k** [comment]
It works fine, thanks!
